HW15/task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls")),
]

HW15/task_manager/tasks/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("search/", views.search, name="search"),
    path("task/<int:task_id>/", views.task, name="task"),
    path("tasks/", views.task_page, name="task_page"),
    path("categories/", views.all_categories, name="all_categories"),
    path("autocomplete_data/", views.autocomplete_data, name="autocomplete_data"),
]

HW15/task_manager/tasks/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Task(models.Model):
    STATUS_CHOICES = (
        ("to-do", "To Do"),
        ("in-progress", "In Progress"),
        ("done", "Done"),
    )
    title = models.CharField(max_length=200)
    description = models.TextField()
    due_date = models.DateField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

HW15/task_manager/tasks/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from .models import Task, Category, Tag
from django.core.paginator import Paginator


def home(request):
    tasks = Task.objects.all()
    paginator = Paginator(tasks, 12)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "home.html", {"page_obj": page_obj})


def search(request):
    query = request.GET.get("query", None)
    if query is not None:
        tasks = Task.objects.filter(title__icontains=query) | Task.objects.filter(
            tags__name__icontains=query
        )
        return render(request, "search.html", {"tasks": tasks})
    else:
        return render(request, "search.html", {})


def task(request, task_id):
    task = Task.objects.get(id=task_id)
    return render(request, "task.html", {"task": task})


def task_page(request):
    tasks_todo = Task.objects.filter(status="to-do")
    tasks_in_progress = Task.objects.filter(status="in-progress")
    tasks_done = Task.objects.filter(status="done")

    context = {
        "tasks_todo": tasks_todo,
        "tasks_in_progress": tasks_in_progress,
        "tasks_done": tasks_done,
    }
    return render(request, "task_page.html", context)


def all_categories(request):
    categories = Category.objects.all()
    return render(request, "categories.html", {"categories": categories})


def autocomplete_data(request):
    task_titles = Task.objects.values_list("title", flat=True)
    tag_names = Tag.objects.values_list("name", flat=True)

    autocomplete_data = list(task_titles) + list(tag_names)

    return JsonResponse(autocomplete_data, safe=False)

HW15/task_manager/tasks/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Task Manager{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  

  <style>
    body {
      background-color: #212335;
      color: #FFFFFF;
    }

    .navbar {
      background-color: #20a773;
    }

    .navbar-toggler {
      border-color: #FFFFFF;
    }

    .navbar-toggler-icon {
      background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 30 30' fill='%23FFFFFF' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='%23FFFFFF' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M4 6h22M4 14h22M4 22h22'/%3E%3C/svg%3E");
    }

    .navbar-nav .nav-link {
      color: #FFFFFF;
    }

    .container {
      margin-top: 30px;
    }

    .navbar-logo {
      max-height: 70px;
      width:150px; 
      margin-right: 10px; 
      transition: all 0.3s ease; 
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2); 
      border-radius: 5px; 
      overflow: hidden; 
    }

    .navbar-logo:hover {
      transform: scale(1.3); 
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); 
    }

    .navbar .categories-link {
      display: none; 
    }

    {% if request.resolver_match.view_name == 'task_page' %}
    .navbar .categories-link {
      display: block;
    }
    {% endif %}
  </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">
        <a href="{% url 'home' %}">
          <img src="{% static 'img/logo.png' %}" alt="Logo" class="navbar-logo">
        </a>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'search' %}">Search</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'task_page' %}">Task List</a>
          </li>
          <li class="nav-item categories-link">
            <a class="nav-link" href="{% url 'all_categories' %}">Categories</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container mt-3">
    {% block content %}
    {% endblock %}
  </div>
  
  
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"></script>

</body>
</html>

HW15/task_manager/tasks/templates/categories.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <style>
      .card {
        background-color: #343a40;
        color: #ffffff;
        border: none;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        margin-bottom: 20px;
      }

      .card-title {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 10px;
      }

      .card-text {
        font-size: 16px;
        margin-bottom: 15px;
      }

      .related-posts {
        list-style: none;
        padding: 0;
        margin: 0;
      }

      .related-posts li {
        margin-bottom: 5px;
      }

      .related-posts li a {
        color: #20a773;
        text-decoration: none;
        transition: color 0.3s ease;
      }

      .related-posts li a:hover {
        color: #188753;
      }
    </style>

    <h1 class="mb-4">All Categories</h1>
    <div class="row">
      {% for category in categories %}
        <div class="col-md-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ category.name }}</h5>
              <p class="card-text">{{ category.description }}</p>

              <h6 class="mb-3">Related Posts:</h6>
              <ul class="related-posts">
                {% for task in category.task_set.all %}
                  <li><a href="{% url 'task' task.id %}">{{ task.title }}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

HW15/task_manager/tasks/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <style>
      body {
        background-color: #212335;
        color: #FFFFFF;
        text-align: center;
      }

      a {
        color: #FFFFFF;
        text-decoration: none; 
      }

      .myCard {
        background-color: transparent;
        width: 190px;
        height: 254px;
        perspective: 1000px;
        margin-bottom: 20px;
        cursor: pointer; 
      }

      .title {
        font-size: 1.5em;
        font-weight: 900;
        text-align: center;
        margin: 0;
      }

      .innerCard {
        position: relative;
        width: 100%;
        height: 100%;
        text-align: center;
        transition: transform 0.8s;
        transform-style: preserve-3d;
        cursor: pointer;
      }

      .myCard:hover .innerCard {
        transform: rotateY(180deg);
      }

      .frontSide,
      .backSide {
        position: absolute;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: space-evenly;
        width: 100%;
        height: 100%;
        -webkit-backface-visibility: hidden;
        backface-visibility: hidden;
        border: 1px solid rgba(255, 255, 255, 0.8);
        border-radius: 1rem;
        color: white;
        box-shadow: 0 0 0.3em rgba(255, 255, 255, 0.5);
        font-weight: 700;
        padding: 10px;
        box-sizing: border-box;
      }

      .frontSide,
      .frontSide::before {
        background: linear-gradient(90deg, rgba(119,191,204,1) 0%, rgba(9,121,92,1) 0%, rgba(0,103,124,1) 100%);
      }

      .backSide,
      .backSide::before {
        background-image: linear-gradient(160deg, #0093E9 0%, #80D0C7 100%);
      }

      .backSide {
        transform: rotateY(180deg);
      }

      .frontSide::before,
      .backSide::before {
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        content: '';
        width: 110%;
        height: 110%;
        position: absolute;
        z-index: -1;
        border-radius: 1em;
        filter: blur(20px);
        animation: animate 5s linear infinite;
      }

      @keyframes animate {
        0% {
          opacity: 0.3;
        }

        80% {
          opacity: 1;
        }

        100% {
          opacity: 0.3;
        }
      }
      .pagination {
        display: flex;
        justify-content: center;
        margin-top: 20px;
        margin-bottom: 20px;
      }


      .pagination .page-link {
        color: #FFFFFF;
        background-color: #188753;
        border: none;
      }

      .pagination .page-link:hover,
      .pagination .page-link:focus {
        background-color: #3186AB;
      }
    .pagination .page-item.active .page-link {
      background-color: #0b3d33;
    }

    .pagination .page-item.active {
      border: 1px solid #0b3d33;
      border-radius: 5px;
    }      

    </style>
    

    <h1>All Tasks</h1>
    <div class="row">
      {% for task in page_obj %}
        <div class="col-md-3">
          <div class="myCard" onclick="window.location='{% url 'task' task.id %}'">
            <div class="innerCard">
              <div class="frontSide">
                <p class="title">{{ task.title }}</p>
                <p>Hover for details</p>
              </div>
              <div class="backSide">
                <p class="title">Details</p>
                <p><strong>Tags:</strong> {% for tag in task.tags.all %}{{ tag.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
                <p><strong>Category:</strong> {{ task.category.name }}</p>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>

    <div class="pagination">
      {% if page_obj.has_previous %}
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}
      
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="page-link active" href="?page={{ num }}">{{ num }}</a>
        {% else %}
          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}
      
      {% if page_obj.has_next %}
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
      {% endif %}
    </div>
  </div>
{% endblock %}

HW15/task_manager/tasks/templates/search.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <style>
      body {
        background-color: #212335;
        color: #FFFFFF;
        text-align: center;
      }

      a {
        color: #FFFFFF;
      }

      .InputContainer {
        width: 100%;
        max-width: 400px;
        height: 50px;
        display: flex;
        align-items: center;
        justify-content: center;
        background: linear-gradient(to bottom, rgb(25, 189, 148), rgb(4, 194, 112));
        border-radius: 30px;
        overflow: hidden;
        cursor: pointer;
        box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.075);
        margin: 20px auto;
      }

      .input {
        width: 90%;
        height: 40px;
        border: none;
        outline: none;
        caret-color: rgb(255, 81, 0);
        background-color: rgb(255, 255, 255);
        border-radius: 30px;
        margin-left: 5px;
        padding-left: 15px;
        letter-spacing: 0.8px;
        color: rgb(19, 19, 19);
        font-size: 13.4px;
      }

      .search-btn {
        width: 70px;
        height: 40px;
        background-color: #4495C3;
        border: none;
        border-radius: 30px;
        padding: 8px;
        margin-left: 5px;
        margin-right: 5px;
        cursor: pointer;
        outline: none;
      }

      .search-icon {
        color: #FFFFFF;
      }

      .card {
        background-color: rgba(255, 255, 255, 0.06);
        border: 2px solid #464C5C;
        border-radius: 6px;
        margin-bottom: 20px;
      }

      .card-title {
        background-color: #188753;
        color: #FFFFFF;
        font-size: 20px;
        padding: 10px;
        border-top-left-radius: 6px;
        border-top-right-radius: 6px;
      }

      .card-body {
        padding: 10px;
      }

      .card-text {
        color: #FFFFFF;
        margin-bottom: 10px;
      }

      .btn-primary {
        background-color: #4495C3;
        border-color: #4495C3;
        margin-top: 10px;
      }

      .btn-primary:hover {
        background-color: #3186AB;
        border-color: #3186AB;
      }

      .btn-primary:focus {
        box-shadow: 0 0 0 0.2rem rgba(68, 149, 195, 0.5);
      }

      .no-results {
        color: #FFFFFF;
        font-style: italic;
        opacity: 0.8;
      }

      .ui-autocomplete {
        max-height: 200px;
        overflow-y: auto;
        background-color: rgba(255, 255, 255, 0.06);
        border: 2px solid #464C5C;
        border-radius: 6px;
        padding: 5px;
        margin-top: 5px;
      }

      .ui-autocomplete .ui-menu-item {
        padding: 5px;
        cursor: pointer;
      }

      .ui-autocomplete .ui-menu-item:hover {
        background-color: #191919;
        color: #FFFFFF;
      }
    </style>

    <h1>Search Tasks</h1>
    <div class="InputContainer">
      <form method="get" action="{% url 'search' %}" style="width: 100%; display: flex;">
        <input type="text" id="input" class="input" name="query" placeholder="Search..">
        <button type="submit" class="search-btn">
          <i class="fas fa-search search-icon"></i>
        </button>
      </form>
    </div>

    <hr class="my-4">

    {% if tasks %}
      {% for task in tasks %}
        <div class="card">
          <h5 class="card-title">{{ task.title }}</h5>
          <div class="card-body">
            <p class="card-text">{{ task.description }}</p>
            <a href="{% url 'task' task.id %}" class="btn btn-primary">View Task</a>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <p class="no-results">No results found.</p>
    {% endif %}
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/smoothness/jquery-ui.css">
  <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>
  <script>
    $(document).ready(function() {
      $.getJSON("{% url 'autocomplete_data' %}", function(data) {
        $("#input").autocomplete({
          source: data,
          minLength: 2, 
        }).autocomplete("instance")._renderItem = function(ul, item) {
          return $("<li>")
            .append("<div>" + item.label + "</div>")
            .appendTo(ul);
        };
      });
    });
  </script>
{% endblock %}

HW15/task_manager/tasks/templates/task.html
{% extends 'base.html' %}

{% block content %}
  <style>
    body {
      background-color: #212335;
      color: #FFFFFF;
      text-align: center;
      margin: 0;
      padding: 0;
    }

    a {
      color: #FFFFFF;
      text-decoration: none;
    }

    .container {
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
    }

    .card {
      background-color: rgba(255, 255, 255, 0.06);
      border: 2px solid #464C5C;
      border-radius: 12px;
      margin-bottom: 20px;
      position: relative;
      width: 80%;
      max-width: 800px;
      height: auto;
      color: #fff;
      transition: 0.5s;
      cursor: pointer;
    }

    .card:hover {
      transform: translateY(-20px);
    }

    .card::before {
      content: '';
      width: 100%;
      height: 100%;
      position: absolute;
      top: 0;
      left: 0;
      background: linear-gradient(45deg, #2bff00, #003cff);
      border-radius: 1.2em;
      opacity: 0;
      transition: opacity 0.5s;
    }

    .card:hover::before {
      opacity: 1;
    }

    .card::after {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: linear-gradient(45deg, #1fb900, #0091ff);
      filter: blur(30px);
    }

    .card span {
      position: absolute;
      top: 12px;
      left: 12px;
      right: 12px;
      bottom: 12px;
      background-color: rgba(0, 0, 0, 0.6);
      z-index: 2;
      border-radius: 1em;
    }

    .card span::before {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      width: 50%;
      height: 100%;
      background-color: rgba(255, 255, 255, 0.1);
    }

    .card .card-body {
      position: relative;
      padding: 20px;
      z-index: 10;
      width: 100%;
      height: 100%;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      font-weight: 800;
      font-size: 2em; 
    }

    .card-text {
      font-size: 1.2em; 
      margin-bottom: 5px;
    }

    .card-text strong {
      font-weight: 600; 
    }

    .card-text:last-child {
      margin-bottom: 0; 
    }

    .card-title {
      font-size: 1.5em;
    }
  </style>

  <div class="container">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">{{ task.title }}</strong></h1>
        <p class="card-text">{{ task.description }}</p>
        <p class="card-text"><strong>Due Date:</strong> {{ task.due_date }}</p>
        <p class="card-text"><strong>Status:</strong> {{ task.status }}</p>
        <p class="card-text"><strong>Category:</strong> {{ task.category.name }}</p>
        <p class="card-text"><strong>Tags:</strong> {% for tag in task.tags.all %}{{ tag.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
      </div>
    </div>
  </div>
{% endblock %}

HW15/task_manager/tasks/templates/task_page.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <style>
      body {
        background-color: #212335;
        color: #FFFFFF;
        text-align: center;
      }

      a {
        color: #FFFFFF;
        text-decoration: none;
      }

      .wireframe {
        font-size: 16px;
      }

      .col {
        border: 2px solid #464C5C;
        border-radius: 6px;
        display: inline-block;
        margin: 10px;
        padding: 6px;
        vertical-align: top;
        width: 30%;
      }

      .col h1 {
        margin: 0;
        padding: 8px;
        border-radius: 5px;
        height: 40px;
        font-size: 18px;
        line-height: 1.5;
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .col ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        min-height: 180px;
      }

      .col li {
        background-color: rgba(255, 255, 255, 0.06);
        border: 2px solid #464C5C;
        border-radius: 6px;
        height: 52px;
        margin: 8px 0;
        padding: 6px;
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .one h1 {
        background-color: #056efd;
      }

      .two h1 {
        background-color: #cb770a;
      }

      .three h1 {
        background-color: #188753;
      }

      .no-tasks {
        color: #FFFFFF;
        font-style: italic;
        opacity: 0.8;
      }

      * {
        box-sizing: border-box;
      }

    </style>


    <section class="wireframe">
      <section class="col one">
        <h1>To Do</h1>
        <ul>
          {% for task in tasks_todo %}
            <li><a href="{% url 'task' task.id %}">{{ task.title }}</a></li>
          {% empty %}
            <li class="no-tasks">No tasks in this section.</li>
          {% endfor %}
        </ul>
      </section>
      <section class="col two">
        <h1>In Progress</h1>
        <ul>
          {% for task in tasks_in_progress %}
            <li><a href="{% url 'task' task.id %}">{{ task.title }}</a></li>
          {% empty %}
            <li class="no-tasks">No tasks in this section.</li>
          {% endfor %}
        </ul>
      </section>
      <section class="col three">
        <h1>Done</h1>
        <ul>
          {% for task in tasks_done %}
            <li><a href="{% url 'task' task.id %}">{{ task.title }}</a></li>
          {% empty %}
            <li class="no-tasks">No tasks in this section.</li>
          {% endfor %}
        </ul>
      </section>
    </section>
  </div>
{% endblock %}